### ISSUE TITLE
Develop OBJECT-BUILDER application (epic)

### ISSUE THREAD

**Issue by ajflynn** [kgrid/kgrid.github.io#7]
+ Identify what "types" of knowledge object payloads may lend themselves to being built into payloads semi-automatically to facilitate creating knowledge objects by type (e.g., linear regression equations payloads may allow for this)
+ Develop an app that is capable of supporting non-programmers to do payload and knowledge object building

**Comment by pboisver** [comment]
Questions, as we spec out this work: 

What is the lifecycle of a KO "being built into payloads semi-automatically" like? How does ownership, publication, collection, curation happen? Is the metadata also generated automatically, say, from a template? The input and output specs? The documentation? 

How are these objects updated and versioned, with respect to the core algorithm? Regenerate them all? When checking out these objects does an activator load them as a collection? Are there additional packaging options (e.g. zip files) that make sense for delivering these objects?

---

For the second bullet point, I'm not sure I fully understand the intent. In effect it suggests a particular approach to solving the problem of making( parameterized) knowledge easier to apply. In addition to the example in the first bullet point (regression equations), it seems meant to cover additional types of parameterized knowledge, but not the types of algorithms a programmer/informatician might implement.  I'll take a stab at what I think it is meant to cover (hypothetically):  

> Let's say we have a class of objects that take genotypic information about a particular patient as input, and contain a guideline for a particular drug (or drug regimen) that depends on that genotypic info. We could, based on the presence/absence of certain markers, make a recommendation for efficacy of the drug or regimen, dosing advice, side effects, etc.

> For any particular object in this class of objects, the important bit of knowledge is reduced to a declarative specification—which markers, which drugs, what recommendations. Something like, "If a & b, but not c, then use drug x, at dose y, for z months." This could be expressed in a number of "non-programming" forms, tables, rdf, domain-specific languages, etc.  
---
So, the "knowledge" of how to apply an appropriate specification could be created once, perhaps by a programmer, and could be separate from the "knowledge" contained in the specification itself. Put the two together and this feels like "payload and knowledge object building" for non-programmers. Maybe one could  even generate many specifications from some underlying source and pipe them through a process that generates KOs wrapping the spec with enough code to apply it to appropriate inputs and generate appropriate outputs (which also sounds like the first bullet point.)

---

In any case, the goal is to make parameterized knowledge (regression equations, specification driven knowledge, etc.) easier to apply, and there are several possible approaches to accomplishing this. Automated, or semi-automated, building of many individual KOs, one per parameter set, or per specification, by non-programmers might be one piece of some potential solutions, but the actual goal is easy application of new or updated knowledge.
